version: '3.3'

services:
  balanceservice:
    container_name: balanceservice
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8001"`
    environment:
      BALANCESERVICE_SERVE_REST_ADDRESS: ":8001"
      BALANCESERVICE_DB_USER: "postgres"
      BALANCESERVICE_DB_PASS: "gv9y3ytsow"
      BALANCESERVICE_DB_NAME: "balanceservice"
  balanceservicedatabase:
    image: "postgres"
    env_file:
      - ./balanceservice/database.env
    volumes:
      - ./balanceservice/database-data:/var/lib/postgresql/data/