version: '3.3'

services:
  rabbitmq:
    image: "rabbitmq:3.6-management"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost ", "5672" ]
      interval: 5s
      timeout: 30s
      retries: 10

  balanceservicedatabase:
    image: "postgres"
    env_file:
      - ./balanceservice/database.env
    volumes:
      - ./balanceservice/database-data:/var/lib/postgresql/data/
      - ./balanceservice/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  balanceservice:
    container_name: balanceservice
    build:
      context: ./balanceservice
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    env_file:
      - ./balanceservice/variables.env
    environment:
      BALANCESERVICE_GRPC_ADDRESS: "127.0.0.1:8012"
      BALANCESERVICE_HTTP_PROXY_ADDRESS: ":8080"
      BALANCESERVICE_DB_PORT: "5432"
      BALANCESERVICE_DB_NAME: "balanceservice"
      BALANCESERVICE_RABBITMQ_HOST: "rabbitmq:5672"
    links:
      - "balanceservicedatabase:database"
      - "rabbitmq:rabbitmq"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    depends_on:
      - rabbitmq
      - balanceservicedatabase

  translationservicedatabase:
    image: "postgres"
    env_file:
      - ./translationservice/database.env
    volumes:
      - ./translationservice/database-data:/var/lib/postgresql/data/
      - ./translationservice/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  translationservice:
    container_name: translationservice
    build:
      context: ./translationservice
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    env_file:
      - ./translationservice/variables.env
    environment:
      TRANSLATIONSERVICE_GRPC_ADDRESS: "127.0.0.1:8011"
      TRANSLATIONSERVICE_HTTP_PROXY_ADDRESS: ":8080"
      TRANSLATIONSERVICE_DB_PORT: "5432"
      TRANSLATIONSERVICE_DB_NAME: "translationservice"
      TRANSLATIONSERVICE_BALANCE_SERVICE_ADDRESS: "balanceservice:8080"
      TRANSLATIONSERVICE_RABBITMQ_HOST: "rabbitmq:5672"
      GOOGLE_APPLICATION_CREDENTIALS: "/text-to-speech-translation-service/top-reef-315512-42fe3ca28b09.json"
    links:
      - "translationservicedatabase:database"
      - "balanceservice:balanceservice"
      - "rabbitmq:rabbitmq"
    depends_on:
      - translationservicedatabase
      - balanceservice
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10